# Rustfmt Configuration
edition = "2021"
max_width = 100
tab_spaces = 2
use_small_heuristics = "Max"
chain_width = 80
wrap_comments = true
format_code_in_doc_comments = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
